spring:
  config:
    activate:
      on-profile: local
  application:
    name: RingRingRing
  datasource:
    url: jdbc:mysql://localhost:3306/ringdb
    username: ringringring
    password: ringpwd
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com 
    port: 587
    username: ringringringproject@gmail.com
    password: vbou tyzq pbna txol
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
      
      
      
    


server:
  port: 9090
  

  
  
