spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ring-project-rds-mysql.chgkg6km2h80.ap-northeast-2.rds.amazonaws.com:3306/ringdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ringringring
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
    
    
server:
  port: 80
  
  
  

     
    
